language: cpp
sudo: required
os:
    - linux

services:
    - docker

before_install:
    - docker pull highperformancecoder/builttravisciimage

script:
#  -  sudo docker build --network=host .
  -  docker run --network=host --security-opt="seccomp=unconfined" -v .:/root highperformancecoder/builttravisciimage "cd /root && xvfb-run make DEBUG=1 AEGIS=1"
